# Generated by Django 2.0.3 on 2018-04-06 14:44

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foss',
            fields=[
                ('fossname', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('fossname',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorialdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('submdate', models.DateField(null=True, verbose_name='date published')),
                ('deadline', models.DateField(verbose_name='date')),
                ('fossname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tut.Foss')),
            ],
        ),
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('user', models.OneToOneField(max_length=15, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=30, verbose_name=django.contrib.auth.models.User)),
                ('password', models.CharField(max_length=20, verbose_name=django.contrib.auth.models.User)),
                ('fossname', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tut.Foss')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tut.Userdetails'),
        ),
        migrations.AlterUniqueTogether(
            name='tutorialdetails',
            unique_together={('tname', 'fossname')},
        ),
    ]
